### ISSUE TITLE
Wrong link to increment/decrement expressions specification

### ISSUE THREAD

**Issue by dnpetrov** [Kotlin/kotlin-spec#49] opened 2020-06-23 12:09 UTC
https://kotlin.github.io/kotlin-spec/sections/statements.html#operator-assignments

> Note: although for most real-world use cases operators ++ and -- are similar to operator assignments, in Kotlin they are expressions and are described in the corresponding section of this specification.

Here "corresponding section" link points to https://kotlin.github.io/kotlin-spec/sections/control--and-data-flow-analysis.html#expressions-1, but it doesn't describe increment/decrement operators and their desugaring at all.
In fact, increment and decrement operators are described in corresponding subsections of https://kotlin.github.io/kotlin-spec/sections/expressions.html#prefix-expressions and https://kotlin.github.io/kotlin-spec/sections/expressions.html#postfix-operator-expressions.

**Comment by ice-phoenix** [comment] 2020-06-23 12:39
Yeah, that was caused by an ambiguous section name. Fixed in 3687f0bf

**Closed by ice-phoenix** 2020-06-23 12:39 UTC
